spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/signal_velocity_sms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET SESSION default_storage_engine=INNODB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
